cc_library(
    name = "pricer_maxclosure",
    srcs = ["pricer_maxclosure.cc"],
    hdrs = ["pricer_maxclosure.h"],
    deps = [
        "//experimental/users/edomoreno/HyperRectangularClustering/src/pricer",
        "//third_party/absl/log",
        "//third_party/absl/log:check",
        "//third_party/absl/status",
        "//third_party/absl/status:statusor",
        "//third_party/absl/strings:str_format",
        "//util/operations_research/graph:ebert_graph",
        "//util/operations_research/graph:max_flow",
    ],
)
